import type { NearbyPlace, PersistedAppState } from './types'

export const defaultState: PersistedAppState = {
  schemaVersion: 3,
  preferences: {
    role: 'companion',
    largeText: false,
    activeTab: 'today',
    selectedDate: '2026-07-18',
  },
  trip: {
    id: 'tokyo-family-2026',
    name: '東京家族慢旅',
    destination: '日本・東京',
    startDate: '2026-07-17',
    endDate: '2026-07-21',
    hotel: {
      name: '淺草格拉斯麗飯店',
      address: '東京都台東區雷門 2-10-2',
      phone: '+000-000-000-000',
    },
    emergencyContact: {
      name: '規劃者（示例）',
      relation: '女兒／本次規劃者',
      phone: '+000-000-000-000',
    },
    members: [
      { id: 'me', name: '旅伴 A（示例）', role: 'companion', status: 'together', phone: '+000-000-000-001' },
      { id: 'planner', name: '規劃者（示例）', role: 'planner', status: 'exploring', phone: '+000-000-000-002' },
      { id: 'companion-b', name: '旅伴 B（示例）', role: 'companion', status: 'together', phone: '+000-000-000-003' },
      { id: 'companion-c', name: '旅伴 C（示例）', role: 'companion', status: 'arrived', phone: '+000-000-000-004' },
    ],
    days: [
      { date: '2026-07-17', items: [] },
      { date: '2026-07-18', items: [
      {
        id: 'item-breakfast',
        time: '08:30',
        title: '飯店早餐',
        location: '飯店 2 樓餐廳',
        address: '東京都台東區雷門 2-10-2',
        transport: '飯店內',
        durationMinutes: 60,
        note: '餐廳入口在電梯右側。',
        accessibility: ['有電梯', '有座位'],
        status: 'done',
      },
      {
        id: 'item-sensoji',
        time: '10:30',
        title: '淺草寺散步',
        location: '雷門入口',
        address: '東京都台東區淺草 2-3-1',
        transport: '步行 8 分鐘',
        durationMinutes: 90,
        note: '仲見世人多，走失時回到雷門旁集合。',
        accessibility: ['平坦路線', '有廁所'],
        status: 'next',
      },
      {
        id: 'item-lunch',
        time: '12:30',
        title: '午餐：釜飯春',
        location: '釜飯春總店',
        address: '東京都台東區淺草 1-14-9',
        transport: '步行 6 分鐘',
        durationMinutes: 75,
        note: '已訂位，報名字「CHEN」。',
        accessibility: ['有座位'],
        status: 'later',
      },
      {
        id: 'item-free',
        time: '14:00',
        title: '自由活動',
        location: '淺草周邊',
        address: '東京都台東區淺草',
        transport: '各自步行',
        durationMinutes: 120,
        note: '16:30 回到集合點。',
        accessibility: ['可隨時休息'],
        status: 'later',
        meeting: {
          name: '淺草文化觀光中心 1 樓',
          time: '16:30',
          address: '東京都台東區雷門 2-18-9',
          note: '在一樓服務台旁的長椅集合。',
        },
      },
      ] },
      { date: '2026-07-19', items: [] },
      { date: '2026-07-20', items: [] },
      { date: '2026-07-21', items: [] },
    ],
    alertDismissed: false,
    updatedAt: '2026-07-18T09:45:00+08:00',
  },
}

export const nearbyPlaces: NearbyPlace[] = [
  {
    id: 'restroom-1',
    type: 'restroom',
    name: '淺草文化觀光中心廁所',
    distance: '350 公尺',
    walkMinutes: 5,
    address: '東京都台東區雷門 2-18-9',
    openStatus: '營業資訊已於 09:30 更新',
    accessibility: '有無障礙廁所與電梯',
    note: '位於 2 樓，可搭乘電梯。',
    sourceUpdatedAt: '示範資料・2026/07/18 09:30',
  },
  {
    id: 'restroom-2',
    type: 'restroom',
    name: '雷門地下停車場公廁',
    distance: '500 公尺',
    walkMinutes: 7,
    address: '東京都台東區雷門 2-12',
    openStatus: '開放狀態未確認',
    accessibility: '無障礙資訊未確認',
    note: '入口靠近雷門通，建議出發前再次確認。',
    sourceUpdatedAt: '示範資料・資料時間未確認',
  },
  {
    id: 'food-1',
    type: 'food',
    name: '釜飯春總店',
    distance: '450 公尺',
    walkMinutes: 6,
    address: '東京都台東區淺草 1-14-9',
    openStatus: '預計營業至 20:00，請再次確認',
    accessibility: '一樓有座位',
    note: '餐點現做約需 25 分鐘。',
    sourceUpdatedAt: '示範資料・2026/07/17',
  },
  {
    id: 'food-2',
    type: 'food',
    name: '淺草むぎとろ 本店',
    distance: '650 公尺',
    walkMinutes: 9,
    address: '東京都台東區雷門 2-2-4',
    openStatus: '營業資訊未確認',
    accessibility: '有電梯，入口有小斜坡',
    note: '以山藥泥料理為主，有椅背座位。',
    sourceUpdatedAt: '示範資料・2026/07/16',
  },
  {
    id: 'rest-1',
    type: 'rest',
    name: '隅田公園休息區',
    distance: '700 公尺',
    walkMinutes: 10,
    address: '東京都台東區花川戶 1',
    openStatus: '戶外公共空間',
    accessibility: '平坦步道，沿途有座椅',
    note: '有樹蔭，可看晴空塔。',
    sourceUpdatedAt: '示範資料・2026/07/18',
  },
]
